### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by bob5731** [automatic-ripping-machine/arm-dependencies#315]
docker run -d
  --name='automatic-ripping-machine'
  --net='bridge'
  --privileged=true
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="automatic-ripping-machine"
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-9152780a-a0e6-3877-b6fd-01ec4b6c22be'
  -e 'ARM_UID'='1001'
  -e 'ARM_GID'='1001'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/favicon.ico'
  -p '8088:8080/tcp'
  -v '/mnt/user/appdata/ARM/':'/home/arm':'rw'
  -v '/mnt/user/appdata/ARM/Music':'/home/arm/Music':'rw'
  -v '/mnt/user/appdata/ARM/config':'/etc/arm/config':'rw'
  -v '/mnt/user/appdata/ARM/logs':'/home/arm/logs':'rw'
  -v '/mnt/user/appdata/ARM/media':'/home/arm/media':'rw'
  --runtime=nvidia
  --gpus all
  --device /dev/sr0
  --device /dev/sg1 '1337server/automatic-ripping-machine:latest'

bcfc6a1d3e1c4ec2c84b57da2e9f8b0503e6b4d1fb62378ff4ac4a27019cbf4d
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

The command failed.

how do I fix it???

**Comment by microtechno9000** [comment]
If you are having an issue setting up and configuring ARM, please post an issue against the main repository

https://github.com/automatic-ripping-machine/automatic-ripping-machine
